apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: puum8fsy7-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/puum8fsy7-java-springboot-gitops